
package UserInterface;

import static deliverycompany.Data.listOfUsers;
import static deliverycompany.Data.listOfWorkers;


public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    public ManagerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkPackageButton = new javax.swing.JButton();
        checkWorkerButton = new javax.swing.JButton();
        showListOfWorkersButton = new javax.swing.JButton();
        editWorkerDataButton = new javax.swing.JButton();
        checkSortingDeptButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        showListOfSortingDeptsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        endButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Firma kurierska");
        setName("Firma kurierska"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Co chcesz zrobić?");

        checkPackageButton.setText("Sprawdź paczkę");
        checkPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPackageButtonActionPerformed(evt);
            }
        });

        checkWorkerButton.setText("Sprawdź pracownika");
        checkWorkerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWorkerButtonActionPerformed(evt);
            }
        });

        showListOfWorkersButton.setText("Wyświetl listę pracowników");
        showListOfWorkersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListOfWorkersButtonActionPerformed(evt);
            }
        });

        editWorkerDataButton.setText("Edytuj dane pracownika");
        editWorkerDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWorkerDataButtonActionPerformed(evt);
            }
        });

        checkSortingDeptButton.setText("Sprawdź sortownię");
        checkSortingDeptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSortingDeptButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setText("Zmień hasło");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        showListOfSortingDeptsButton.setText("Wyświetl listę sortowni");
        showListOfSortingDeptsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListOfSortingDeptsButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Wyloguj się");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        endButton.setText("Zakończ");
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showListOfSortingDeptsButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editWorkerDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePasswordButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(checkPackageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(showListOfWorkersButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkSortingDeptButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkWorkerButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(showListOfWorkersButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(checkPackageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkWorkerButton)
                            .addComponent(showListOfSortingDeptsButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSortingDeptButton)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editWorkerDataButton)
                    .addComponent(changePasswordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(endButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        SaveChangesFrame save = new SaveChangesFrame("end");
        save.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_endButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        ManagerChangePasswordFrame changePassword = new ManagerChangePasswordFrame();
        changePassword.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void editWorkerDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWorkerDataButtonActionPerformed
        ManagerEditWorkerFrame editWorker = new ManagerEditWorkerFrame();
        editWorker.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editWorkerDataButtonActionPerformed

    private void checkSortingDeptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSortingDeptButtonActionPerformed
        ManagerCheckSortDeptFrame checkSortDept = new ManagerCheckSortDeptFrame();
        checkSortDept.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkSortingDeptButtonActionPerformed

    private void showListOfSortingDeptsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListOfSortingDeptsButtonActionPerformed
        ManagerShowListOfSortingDeptsFrame showList = new ManagerShowListOfSortingDeptsFrame();
        showList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_showListOfSortingDeptsButtonActionPerformed

    private void checkWorkerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWorkerButtonActionPerformed
        ManagerCheckWorkerFrame check = new ManagerCheckWorkerFrame();
        check.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkWorkerButtonActionPerformed

    private void checkPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPackageButtonActionPerformed
        ManagerCheckPackageFrame check = new ManagerCheckPackageFrame();
        check.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkPackageButtonActionPerformed

    private void showListOfWorkersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListOfWorkersButtonActionPerformed
        ManagerShowListOfAllWorkersFrame showList = new ManagerShowListOfAllWorkersFrame();
        showList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_showListOfWorkersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton checkPackageButton;
    private javax.swing.JButton checkSortingDeptButton;
    private javax.swing.JButton checkWorkerButton;
    private javax.swing.JButton editWorkerDataButton;
    private javax.swing.JButton endButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton showListOfSortingDeptsButton;
    private javax.swing.JButton showListOfWorkersButton;
    // End of variables declaration//GEN-END:variables
}
